server:
  port: 8080
  servlet:
    context-path: ""
spring:
  application:
    name: "@pom.artifactId@"
  redis:
    host: localhost
    port: 6379


logging:
  root:
    level: debug

dove:
  oauth2:
    jwt:
      secret: nicaicaikan