server:
  port: 8081
  servlet:
    context-path: ""
spring:
  application:
    name: "@pom.artifactId@"
  redis:
    host: localhost
    port: 6379


security:
  oauth2:
    #    client:
    #      client-id: uac-client
    #      client-secret: uac-secret-8888
    #      user-authorization-uri: http://localhost:8080/oauth/authorize
    #      access-token-uri: http://localhost:8080/oauth/token
    #    resource:
    #      id: uac-client
    #      user-info-uri: user-info
    #    authorization:
    #      check-token-access: http://localhost:8080/oauth/check_token
    resource:
      jwt:
        # 获取 jwt-secret
        #        key-uri: http://localhost:8080/oauth/token_key
        key-value: nicaicaikan

dove:
  oauth2:
    ignore:
      urls: /test/**,/common/**